name: freecol # you probably want to 'snapcraft register <name>'
base: core20
compression: lzo
version: '0.12.0+git-20220615'
summary: Colonization Strategy Game
description: 'FreeCol is a turn-based strategy game based on the old game
  Colonization, and similar to Civilization. The objective of the game is
  to create an independent nation.
  
  You start with only a few colonists defying the stormy seas in their search
  for new land. Will you guide them on the Colonization of a New World?'


grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots


parts:
  freecol:
    plugin: dump
    source: https://github.com/FreeCol/freecol/releases/download/latest/freecol-git-20220615.zip
    source-type: zip
    build-packages:
      - ca-certificates
      - ca-certificates-java
    stage-packages: [openjdk-11-jre]
    prime:
      - -freecol/freecol.cmd
      - -freecol/developer.pdf
      - -freecol/freecol
    override-prime: |
      snapcraftctl prime
      sed -i "s/^Icon=data\/freecol.png/Icon=freecol\/data\/freecol.png/" freecol/freecol.desktop
      sed -i "s/^Exec=freecol/Exec=freecol-launch.sh/" freecol/freecol.desktop

  freecol-launch:
    plugin: dump
    source: launcher/
    after: [freecol]

  sound-support:
    plugin: dump
    source: sound-support/
    stage-packages: [libasound2, libasound2-plugins, libpulse0]


apps:
  freecol:
    extensions: [gnome-3-38]
    command: freecol-launch.sh
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH
      PULSE_PROP_OVERRIDE: media.role='game'
      ALSA_CONFIG_PATH: $SNAP/asound.conf
    plugs:
      - audio-playback
      - pulseaudio
      - network-bind
      - home
    desktop: freecol/freecol.desktop


layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

